/*
 * Copyright 2014 Gregory Prisament
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <unistd.h>
#include <string.h>

static const char *TEMPLATE =
"# AUTO-GENERATED BY raspbian-wifi-config-from-usb"
"auto lo\n"
"\n"
"iface lo inet loopback\n"
"iface eth0 inet dhcp\n"
"\n"
"auto wlan0\n"
"allow-hotplug wlan0\n"
"iface wlan0 inet dhcp\n"
"    wpa-ssid \"%s\"\n"
"    wpa-psk \"%s\"\n";


/*
 * Returns interface file contents as newly allocated string.
 * Caller must free() result when finished with it.
 */
static char *gen_interface_contents(const char *ssid, const char *psk)
{
    char *buf = calloc(1, 2048);
    if (!buf)
    {
        fprintf(stderr, "Alloc failed in gen_interface_contents");
        return NULL;
    }
    snprintf(buf, 2048, TEMPLATE, ssid, psk);
    return buf;
}


/* 
 * Compares contents of the file named <filename> to <contents>.
 */ 
static bool compare_interfaces_file(bool *outMatch, const char *filename, const char *contents)
{
    FILE *fp = NULL;
    bool result = false;
    bool match;
    char buf[2048];
    size_t read;

    fp = fopen(filename, "r");
    if (!fp)
    {
        fprintf(stderr, "Could not open %s for read\n", filename);
        goto cleanup;
    }

    read = fread(buf, 1, 2048, fp);
    buf[read] = 0;
    match = !strcmp(buf, contents);
    /*printf("buf------------------------------------------------------------------------\n%s", buf);
    printf("contentes-------------------------------------------------------------------\n%s", contents);
    printf("----------------------------------------------------------------------------\n");*/
    if (match)
        printf("Contents match.\n");
    else
        printf("Contents changed.\n");

    result = true;
    *outMatch = match;
cleanup:
    if (fp)
        fclose(fp);
    return result;
}

static bool write_interfaces_file(const char *destFilename, const char *contents)
{
    FILE * fp = NULL;
    bool result = false;

    fp = fopen(destFilename, "w+");
    if (!fp)
    {
        fprintf(stderr, "Could not open %s for write\n", destFilename);
        goto cleanup;
    }


    fprintf(fp, "%s", contents);
    printf("Writing contents to %s\n", destFilename);

    result = true;

cleanup:
    if (fp)
        fclose(fp);

    return result;
}

static bool check_usb_drives_for_wifi_config()
{
    FILE *fp = NULL;
    const char * filesToTry[] = {
        "/media/usb/canopy-wifi.conf",
    };
    char *ssid = NULL;
    char *psk = NULL;
    bool result;
    int i;
    for (i = 0; i < sizeof(filesToTry)/sizeof(filesToTry[0]); i++)
    {
        printf("Check for %s\n", filesToTry[i]);
        fp = fopen(filesToTry[i], "r");
        if (fp)
        {
            printf("Found!\n");
            break;
        }
        else
        {
            printf("Not found.\n");
        }
    }
    if (fp)
    {
        char *ssid = NULL;
        size_t len = 0;
        ssize_t read;
        char *contents = NULL;
        bool match;
        /* Found canopy-wifi.conf file.
         * Read its contents.
         */
        read = getline(&ssid, &len, fp);
        if (read <= 0)
        {
            fprintf(stderr, "Unable to read ssid\n");
            fclose(fp);
            return false;
        }
        ssid[read-1] = 0;
        read = getline(&psk, &len, fp);
        if (read <= 0)
        {
            fprintf(stderr, "Unable to read psk\n");
            fclose(fp);
            return false;
        }
        psk[read-1] = 0;

        contents = gen_interface_contents(ssid, psk);
        if (!contents)
        {
            fprintf(stderr, "Could not generate interface file contents\n");
            fclose(fp);
            return false;
        }
        /* Compare to existing interfaces file.  Only continue if
         * anything changed.
         */
        result = compare_interfaces_file(&match, "/etc/network/interfaces", contents);
        if (!result)
        {
            fprintf(stderr, "Problem comparing to current interface file\n");
            free(contents);
            fclose(fp);
            return false;
        }

        if (!match)
        {
            /* Generate interfaces file */
            result = write_interfaces_file("/etc/network/interfaces", contents);
            if (!result)
            {
                fprintf(stderr, "Problem writing to file\n");
                fclose(fp);
                free(contents);
                return false;
            }

            /* Restart networking service */
            system("service networking restart");
            free(contents);
        }
    }
    if (fp)
        fclose(fp);
    return true;
}

int main(void)
{
    while (1)
    {
        printf("Check USB drives\n");
        check_usb_drives_for_wifi_config();

        sleep(5);
    }
}
